### ISSUE TITLE
Menu options should populate based on the caterer selected

### ISSUE THREAD

**Issue by kskenandore** [kskenandore/CDCC-Scheduler#10]
When a certain caterer is selected in the dropdown menu while creating a new reservation, the menu options for that caterer should be displayed in the next dropdown menu. 

How can we do this? PHP? Javascript?

**Comment by chasonmj** [comment]
I agree that is how that should work however I'm going to comment out those areas of the form because they aren't required in the minimum requirements.  We can add back if we have time.  :)
