### ISSUE TITLE
Admin Functionality

### ISSUE THREAD

**Issue by chasonmj** [kskenandore/CDCC-Scheduler#24]
The case study document says "employees are also not expected to change and so the data can be
entered directly into the database for the purposes of the prototype, but UIs must
reflect where applicable that a manager must be able to create, retrieve, update
and terminate an employee’s record although it need not be functional"

Not sure the best way to tackle this one...

**Comment by kskenandore** [comment]
Created user admin tab where admin can create new employees, edit their information, or delete them upon termination.
