### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by kskenandore** [kskenandore/CDCC-Scheduler#36]
- can we make the login page work?
- can we check to see if an admin is logged in before allowing user to create, edit, delete employees?

**Comment by chasonmj** [comment]
I was wondering if a fully functional security system was necessary for the prototype.  It is a big add but if time permits we can certainly try.

**Comment by chasonmj** [comment]
Full security functionality has been added.  

Admin Login: underwoodh1@cdcc.com, pass: test
User login: wallacek1@cdcc.com, pass: test
